name: mofi
description: A mobile app for mobile finances.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.12
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.5
  dartz: ^0.10.1
  drift: ^1.5.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  flutter_iconpicker: ^3.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_slidable: ^1.2.0
  flutter_sticky_header: ^0.6.1
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  page_indicator: ^0.4.1
  path: ^1.8.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.5
  syncfusion_flutter_datepicker: ^20.1.48
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.8
  drift_dev: ^1.5.2
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  lint: ^1.8.2

flutter_native_splash:
  background_image: assets/images/splash_background.png
  background_image_dark: assets/images/splash_background_dark.png
  image: assets/images/splash_icon.png
  image_dark: assets/images/splash_icon_dark.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
