// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIpIK-ZBB5rfYQf7tjHCleSQITrSkp5g',
    appId: '1:970340898687:web:421c00ce2e836cd85eac4a',
    messagingSenderId: '970340898687',
    projectId: 'mofi-flutter',
    authDomain: 'mofi-flutter.firebaseapp.com',
    storageBucket: 'mofi-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvds_rutn48mHDrhWC-2OVpkFDP5QpHo',
    appId: '1:970340898687:android:107bebede68814fe5eac4a',
    messagingSenderId: '970340898687',
    projectId: 'mofi-flutter',
    storageBucket: 'mofi-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXUGVT9cR-hsOJ2J5y7e_TicV0kqq4Rw',
    appId: '1:970340898687:ios:e251f1c44240f0185eac4a',
    messagingSenderId: '970340898687',
    projectId: 'mofi-flutter',
    storageBucket: 'mofi-flutter.appspot.com',
    iosClientId: '970340898687-kmphbbje1ub4dat423l408nvrvfc5hrn.apps.googleusercontent.com',
    iosBundleId: 'com.thomasviana.mofi',
  );
}
