// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcth5EpF0lnmSGF78zKrx8LxzMthrpAz4',
    appId: '1:214668990940:web:5ece7c184dd6dd8c14d719',
    messagingSenderId: '214668990940',
    projectId: 'mofi-flutter-dev-33c2a',
    authDomain: 'mofi-flutter-dev-33c2a.firebaseapp.com',
    storageBucket: 'mofi-flutter-dev-33c2a.appspot.com',
    measurementId: 'G-LSJX3KNETQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXPmd3_zPPuTqdanHowFTjPCZtmqbZ1c',
    appId: '1:214668990940:android:3c7f835ce5233b8b14d719',
    messagingSenderId: '214668990940',
    projectId: 'mofi-flutter-dev-33c2a',
    storageBucket: 'mofi-flutter-dev-33c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZJlTiyKwcQQmb8yJj7bgqnS9u34Ukis',
    appId: '1:214668990940:ios:e817a698460bdb2414d719',
    messagingSenderId: '214668990940',
    projectId: 'mofi-flutter-dev-33c2a',
    storageBucket: 'mofi-flutter-dev-33c2a.appspot.com',
    iosClientId:
        '214668990940-b2rs6ctp5d3mp32oimqlhvviadb562bb.apps.googleusercontent.com',
    iosBundleId: 'com.thomasviana.mofi.dev',
  );
}
