// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IVqNDRIC1MSIktvDF9tnijLrC1acbPY',
    appId: '1:342857845929:web:a66530f373e4fddc796db8',
    messagingSenderId: '342857845929',
    projectId: 'mofi-flutter-prod-688ca',
    authDomain: 'mofi-flutter-prod-688ca.firebaseapp.com',
    storageBucket: 'mofi-flutter-prod-688ca.appspot.com',
    measurementId: 'G-0RZX37PJ6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFr4Xw5hk-cWuohRHsydGCw97uUhLF2nw',
    appId: '1:342857845929:android:570ed70c19f8b298796db8',
    messagingSenderId: '342857845929',
    projectId: 'mofi-flutter-prod-688ca',
    storageBucket: 'mofi-flutter-prod-688ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjJgitM13kb8U3aBoZS6olZUs1tf8MH-c',
    appId: '1:342857845929:ios:82d49522e8e96dd6796db8',
    messagingSenderId: '342857845929',
    projectId: 'mofi-flutter-prod-688ca',
    storageBucket: 'mofi-flutter-prod-688ca.appspot.com',
    iosClientId: '342857845929-1u5j3ioo06alg9p5dip7cs82q65b8002.apps.googleusercontent.com',
    iosBundleId: 'com.thomasviana.mofi',
  );
}
